---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: openebs
      namespace: openebs
  values:
    image:
      repository: vaultwarden/server
      tag: 1.29.0
    env:
      DOMAIN: https://vaultwarden.${SECRET_DOMAIN}
      # ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
      SIGNUPS_ALLOWED: true
      # YUBICO_CLIENT_ID: ${VAULTWARDEN_YUBICO_CLIENT_ID}
      # YUBICO_SECRET_KEY: ${VAULTWARDEN_YUBICO_SECRET_KEY}
      WEBSOCKET_ENABLED: true
      # SMTP_HOST: ${ROUTER_IP}
      # SMTP_PORT: 25
      # SMTP_FROM: admin@${DOMAIN}
      # SMTP_SECURITY: "off"
    service:
      main:
        ports:
          http:
            port: &port 80
          websocket:
            enabled: true
            port: &websocket-port 3012
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: &host "vaultwarden.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *port
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: *websocket-port
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: *port
        tls:
          - hosts:
              - *host
      admin:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: *host
            paths:
              - path: /admin
                pathType: Prefix
        tls:
          - hosts:
              - *host
    volumeClaimTemplates:
      - name: data
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 200Mi
        storageClass: openebs-hostpath
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 300Mi
