apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:lPe7Xug=,iv:182/2yHKlt+zvEzQYyWTa/9btfR1NsUXijH1aY2ziDM=,tag:plH99gQZPZgJkX5/vREpXQ==,type:str]
    admin-password: ENC[AES256_GCM,data:Fvm61gYUk38Ssyw=,iv:r713PaQgilUoF5tjHifr90Pu7jMWx8ZGMugh9VMKlek=,tag:fHpvNq2LkzLSO9g1bcjo8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17l6a96nngcynk2ncu923k5lv43ccmz797ww855g5xfr7tjqzyars3py2x5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVU9JZW5INndzZGZ6YUZG
            YjdQb01ZQS9NNGNrcVA0KzJ6aW4vaGMvRENNCmlibGVJRlhBVXdKb0JVK0tvOE1u
            YUhGZG1GcXdzRDVHSVRaTU9uaWp1K3cKLS0tIE1sMmdYaHdOTHI0ZmtaZzEvSjJI
            ME1ZLzVxNEtLcVdkVFZ6OWFMdm1Pek0KrWGPQhV0tqx6mfDtHp2Y/1GGqAo6wh33
            WOZBQ1zNYsYUGbYVkb60cQg6opYs+r1GSloImnkJm7x3e82I3RBSkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-28T09:10:28Z"
    mac: ENC[AES256_GCM,data:QXc8YxUtu5BjemUEihlmU8qARBsIDXKAbzNDfDv7Ou2WootRL+fwT3cgzn10wrxgTR3WSlMB0cH7wjNvZMhIRGM2s+NyZ3dkWoIl0KWUFZCH/4uQpCVTezr6RS0+mDqfU3zoqYkT4j1RPivub8SMzQ4onhUPPqEt+AuZ6pNQSKM=,iv:Z5iDxRSPuyCt4eJ9Li2P//0/RiXobVJvGY462Dhzw/w=,tag:5ejq+xkZEm/LHojD4mfLQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
