apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:7sxaucQ1xzCoidiJTPOjICB/WHBTsFBYMOvdZgWrcgMPOgbdzjIkcg==,iv:Vj8Jv7gpacCZu+88uMJFmbH6ixuDb8s7PfxECKayxJQ=,tag:GV8fpn+D3HVcxBQG8RTmaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17l6a96nngcynk2ncu923k5lv43ccmz797ww855g5xfr7tjqzyars3py2x5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMXlraDJwWXBwbTIrUHdI
            Mkx5NlVCUDRwZTc2eXNKTEhQemg3cnVRWGdrCmhMR2tNZTB6eUxMb1VoZFJrcFlM
            cHQrcEQxd3JFUVQ3WTAwc0FHWmtUSVUKLS0tIGFpaVJHU0pvL29vNytZeHhHU0Jt
            bTJVYVNsSnJ3Z3NkaXJHQ3d5L2o2ZTQKYzqCxiMYr1VuVRWh1M+GDgOol/YfEQYv
            t5tkkfp4MLgW+UVBhcWzUJ7K6ewbMnPsQy+7AhUkpE6EuRLljJTqog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-28T09:10:28Z"
    mac: ENC[AES256_GCM,data:EbK6xbXiDXYAd7QAiykHvKPTiHDx9M7JKLhBGFcMe9O+VbSbYYA7kszEbvBzhXsU8GmVQYLjJmQBUWGQmABX8/4quYhLtirU9PkdSHpvSPiHyhnqo6E9tslMnxD/RXrbzogg3n2EmHZJ90FUDF0rxtDKg7osRyXPW+6ltY1tOXc=,iv:ImPQJ9R6ih0//bTcBVuJY7m3nVS03iymEgONaXUVfXI=,tag:VUAXWi0whXRN9wsPGtO1gQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
