apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:nnVraTc=,iv:9KFcURC8gA9FoiMR8QgQZ3uGUQyk6RK/onpI1Xl+uts=,tag:HB64SWvUMmxd2sidUuAFyg==,type:str]
    password: ENC[AES256_GCM,data:M5r0lPM3/AHnnEUSv+r8ISvlX/1dVhAF64L5I+JDqFjPZjYyW3MNtKiW4V+US8zY9Eo0ouIY50T1JKeu,iv:o03IIngkYcA5oSQQhSMz4bR12kjCLOYNorCsP3qD6As=,tag:IGQ4/k8W2+62rJJkINpVuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17l6a96nngcynk2ncu923k5lv43ccmz797ww855g5xfr7tjqzyars3py2x5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdUVoK2RMeHpXeTk5K2M3
            aEdKQi9tSHdkakJuOGpncFBOUkU4a2x0Zmp3CmVwek5CL0RCZXdtZHB2QjZQRy93
            UlV5aGcwNlNva0ZiWXhSNHhzeUxaUkEKLS0tIGhQY1Uva0hrY2Y5UE4ydy9WdDFu
            cGVoYVB6VW5YM2YvaE96WkN5SG8xWk0K3xwe+azwkKd3EkjXYJ1/FG3/OoGOIkYe
            wTPI8XUS4pD09Ttl1+IRFu+M8mfYO8KuI+zBZubGCwh/y4NGMbVSHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-28T09:10:28Z"
    mac: ENC[AES256_GCM,data:pMFgGAeko/+3UOhHCASfYaRdWVt0dKq71lms7u66i8VrBQ5gILlhs0cgF/Ctndazh3BBQDbd67E6oImKEjBQTZYe0yK5OMYNF0l6TQj3BTN+PrHxkSioEyA9u5qySXXB1R0azSU3E/p37sxwZzc2xK4FQZ/MAc3XPh00niN60UQ=,iv:JctpmpBIe/Z3el32kAJbmM1NOez5SiY9/v3/eafVaEA=,tag:XcgSHXVhZ9VfQj63A2ANZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
