---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs-localpv
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: openebs-localpv
      version: v3.4.0
      sourceRef:
        kind: HelmRepository
        name: openebs-localpv
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    deviceClass:
      nodeAffinityLabels:
        - "kubernetes.io/hostname=y9000p"
      fsType: "ext4"
